#!/bin/sh

# Copyright © 2016 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>

# Created: 2016-08-17
# Last changed: 2016-08-17 18:20:08

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

URL="https://raw.githubusercontent.com/centreon-deb"
BOOTSTRAP="debian/bootstrap"

PKGS="
centreon-clib:1.4.2
centreon-engine:1.5.0
centreon-broker:2.11.4
centreon-connectors:1.1.1
php-archive-zip:0.1.2
php-db-dataobject:1.11.5
php-db-dataobject-formbuilder:1.0.2
php-log:1.13.1
php-mdb2:2.5.0b5
php-validate:0.8.5
"
for pkg in $PKGS; do
    p=$(echo $pkg | cut -d: -f 1)
    v=$(echo $pkg | cut -d: -f 2)
    curl $URL/$p/$BOOTSTRAP | sh
    cd $p
    git deb-pkg -C -U -u $v -d origin/debian build
    cd -
done
