#!/bin/sh

# Copyright © 2016 renard <seb@chezwam.org>

# Created: 2016-08-17
# Last changed: 2016-08-17 18:11:54

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.


if test -z "$1"; then
    echo "$0 var-definition-file"
    exit 1
fi

IFS='
'

URL='http://download.pear.php.net/package/'
. $1

for V in $VERSIONS; do
    v=$(echo $V | awk '{print $1}')
    d=$(echo $V | awk '{$1="";  sub("^ ", ""); print}')
    wget $URL/$PACKAGE-$v.tgz
    tar xzf $PACKAGE-$v.tgz
    rm -f $PACKAGE-$v.tgz
    git add .
    git commit --signoff -m "Import from $v" --date="$d"
    git tag -d $v
    git tag -a -m "Version $version from $d" $v HEAD
    rm -rf *
done
git checkout .

